import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider, SignedOut, SignedIn, SignInButton, UserButton, SignIn } from "@clerk/nextjs";
import {  neobrutalism } from '@clerk/themes'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme:  neobrutalism,
      }}
    >
      <html lang="en">
        <body>
          <header>
            <SignedOut>
              <div className="flex justify-center">
                {/* <SignIn 
                  // appearance={{
                  //   elements: {
                  //     formButtonPrimary: 'bg-slate-500 hover:bg-slate-400 text-sm',
                  //     formButtonSecondary: 'bg-gray-500 hover:bg-gray-400 text-sm', 
                  //   },
                  // }} 
                />  */}
              </div>
            </SignedOut>
            <SignedIn  appearance={{
              elements: {
                formButtonPrimary: 'bg-blue-500 hover:bg-red-400 text-sm',
              },
            }}>
              <UserButton />
            </SignedIn>
          </header>
          <main>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  )
}
